#ifndef LANSELECTMODE_H
#define LANSELECTMODE_H

#include "JSystem/J2D/J2DAnimation.h"
#include "JSystem/J2D/J2DPicture.h"
#include "JSystem/J2D/J2DScreen.h"
#include "JSystem/ResTIMG.h"
#include "dolphin/types.h"
#include "macros.h"
#include <JSystem/J2D/J2DPane.h>
#include <JSystem/JKernel/JKRArchive.h>

class LANSelectMode { // Autogenerated
public:
    enum Color {
        cLanColor_0,
        cLanColor_1,
        cLanColor_2,
    };

    class Background {
    public:
        Background(JKRArchive *archive) {
            _120 = 0;
            _122 = 0;
            setup(archive);
        }

        void setup(JKRArchive *);
        void calc();

        void draw(const J2DGrafContext *graf) {
            mScreen.draw(0.0f, 0.0f, graf);
        }

        // Inline/Unused
        ~Background();
    private:
        J2DScreen mScreen;
        J2DAnmTransform *_118;
        J2DAnmTextureSRTKey*_11c;
        s16 _120;
        s16 _122;
        PLACEHOLDER_BYTES(0x124, 0x128);
    }; // Size: 0x128?

    class Item {
    public:
        
        // Inline/Unused
        Item(u32, J2DScreen *, void *);
        void selectIn();
        void selectOut();
        void unselect();

        virtual void update() {} // 0x802158b0
        virtual void calc(); // 0x80212e50
        virtual bool changeValueUp() { return false; } // 0x80216018
        virtual bool changeValueDown() { return false; } // 0x80216020
        virtual void changeColor(Color); // 0x80212dac

        void changeTex(ResTIMG *paImg) {
            _c->changeTexture(paImg, 0);
        }        
    protected:
        int _4;
        J2DPane *_8;
        J2DPicture *_c;
        J2DAnmTransform*_10;
        s16 _14;
    }; // Size: 0x18

    class SelectableItem : public Item {
    public:
        SelectableItem(u32, J2DScreen *, void *, void *, void *, int, int, u32); // 0x80212f00
        bool changeValueUp(); // 0x802132d8
        bool changeValueDown(); // 0x802133c8

        void update(); // 0x802134b4
        void calc(); // 0x8021350c

        // Inline/Unused
        void setMask(u32);
        void setMax(int);

        int get_18() {
            return _18;
        }
    protected:
        int _18;
        int _1c;
        u32 _20;
        int _24;
        J2DAnmTransform *_28;
        J2DAnmTransform *_2c;
        J2DAnmTextureSRTKey *_30;
        J2DAnmTevRegKey *_34;
        J2DAnmTevRegKey *_38;
        J2DPane *_3c;
        J2DPane *_40;
        s16 _44;
        s16 _46;
        s16 _48;
        s16 _4a;
        s16 _4c;
    }; // size: 0x50? (padded)

    class SelectableItem1 : public SelectableItem {
    public:
        virtual void changeColor(Color); // 0x80213770
        void calc(); // 0x80213884

        // Inline/Unused 
        SelectableItem1(u32, J2DScreen *, void *, void *, void *, ResTIMG **, int);
    
        // Fabricated Inlines
        void changeImg(ResTIMG **paImg) {
            _54 = paImg;
            _50->changeTexture(_54[_18], 0);

        }    
    protected:
        J2DPicture *_50;
        ResTIMG **_54;
    }; // Size: 0x58

    class SelectableItem2 : public SelectableItem {
    public:
        virtual void changeColor(Color); // 0x80213b3c
        void calc(); // 0x80213cc0

        // Inline/Unused
        SelectableItem2(u32, J2DScreen *, void *, void *, void *);
    private:
        J2DPicture *_50;
        J2DPicture *_54;
    };

    class SelectableItemDisp : public SelectableItem {
    public:
        void changeColor(Color); // 0x80214088
        void calc(); // 0x802142ec

        // Inline/Unused
        SelectableItemDisp(u32, J2DScreen *, void *, void *, void *);
    private:
        J2DPicture *_50;
        J2DPicture *_54;
        J2DPicture *_58;
        J2DAnmTevRegKey *_5c;
        s16 _60;
    }; // Size: 0x64

    class SelectableItemSw : public SelectableItem1 {
    public:
        enum ValueMode {
            cValueMode_0,
            cValueMode_1,
        };
        void changeValueMode(ValueMode); // 0x80213fc0

        ValueMode getValueMode() {
            return _58;
        }

        // Inline/Unused
        SelectableItemSw(u32, J2DScreen *, void *, void *, void *, ResTIMG **, ResTIMG **, int, ResTIMG **, int);
        void setMaskSw(u32);
    private:
        ValueMode _58;
        int _5c;
        int _60;
        u32 _64;
        ResTIMG **_68;
        ResTIMG **_6c;
    }; // Size: 0x70
    
    LANSelectMode(JKRArchive *); // 0x8021462c
    void directView(int); // 0x802158b4
    int calc(); // 0x80215c9c
    void calcAnm(); // 0x80216028
    void draw(const J2DGrafContext *); // 0x802161ac
    void start(bool); // 0x80216214
    void setDisplayMax(); // 0x80216358    
    
private: 
    u32 mState;
    bool _4;
    bool _5;
    Background mBackground;
    J2DScreen mScreen; // foreground?
    J2DAnmBase *_248;
    s16 _24c;
    int _250;
    int _254;
    SelectableItem1 *_258;
    SelectableItem1 *_25c;
    SelectableItem2 *_260;
    SelectableItem1 *_264;
    SelectableItemSw *_268;
    SelectableItem1 *_26c;
    SelectableItemDisp *_270;
    Item *mItem;
    Item *_278[8];
    ResTIMG *_298[3];
    ResTIMG *_2a4[4];
    ResTIMG *_2b4[2];
    ResTIMG *_2bc[7];
    ResTIMG *_2d8;
    ResTIMG *_2dc;
    ResTIMG *_2e0;
    ResTIMG *_2e4[2];
    ResTIMG *_2ec[16];
    ResTIMG *_32c[6];
    ResTIMG *_344[2];
    PLACEHOLDER_BYTES(0x34c, 0x350);
}; // class LANSelectMode

extern const char *cpaGameModeTex[];
extern const char *cpaCrsOrderTex[];
extern const char *cpaCrsNameTex[];
extern const char *cpaStageOrderTex[];
extern const char *cpaLabelNameTex[];
extern const char *cpaTagTex[];

#endif // LANSELECTMODE_H
