object: orig/MarioClub_us/main.dol
hash: db87a9ec1a34275efc45d965dcdcb1a9eb131885
#map: orig/MarioClub_us/debugInfoM.MAP
symbols: config/MarioClub_us/symbols.txt
splits: config/MarioClub_us/splits.txt
mw_comment_version: 8