path: orig/main.dol
r13: 0x8041bf80
r2: 0x8041f1c0

section_defs:
    text:
        .init:
        .text:
    data:
        extab_:
            attr: a
        extabindex_:
            attr: a
        .ctors:
        .dtors:
        .BINARY:
            attr: wa
        .rodata:
        .data:
        .sdata:
        .sdata2:
    bss:
        .bss:
        .sbss:
        .sbss2:
            nobits: true