global:
 # .init
 0x80003100: __check_pad3
 0x80003140: __set_debug_bba
 0x8000314c: __get_debug_bba
 0x80003154: __start
 0x800032b0: __init_registers
 0x80003340: __init_data
 0x80003400: __init_hardware
 0x80003424: __flush_cache
 0x80003458: memset
 0x80003488: __fill_mem
 0x80003540: memcpy
 0x80003590: TRK_memset
 0x800035c0: TRK_memcpy
 0x80005518: __TRK_reset

 # kartLocale.cpp:
 #.text
 0x800056c0: localize__10KartLocaleFv
 #.data
 0x803879c0: mscpaLanguageName__10KartLocale
 #.sdata
 0x80413f80: msCountry__10KartLocale
 0x80413f84: msRegion__10KartLocale
 0x80413f88: msDatingMode__10KartLocale
 #.sbss
 0x804156e0: msLanguage__10KartLocale
 0x804156e4: msSpeedUnit__10KartLocale
 0x804156e8: msVideoMode__10KartLocale
 0x804156ec: msVideoFrameMode__10KartLocale

 # random.cpp
 0x800693c8: __ct__Q25JMath13TRandom_fast_FUl

 # JUTAssert.cpp
 0x80069af4: getSDevice__12JUTAssertionFv
 0x80069bd8: showAssert_f__12JUTAssertionFUlPCciPCce

 # JKRHeap.cpp
 0x80084d9c: __nw__FUl
 0x80084e28: __nw__FUli
 0x80084eb8: __nw__FUlP7JKRHeapi
 0x80084fa4: __nwa__FUl
 0x80085030: __nwa__FUli
 0x800850c0: __nwa__FUlP7JKRHeapi
 0x800851ac: __dl__FPv
 0x800851d0: __dla__FPv

 # OSError.c
 0x800eeaec: OSPanic

 # NMWException.cp
 0x80105af8: __destroy_new_array
 0x80105b74: __destroy_arr
 0x80105bec: __construct_array
 0x80105ce8: __dt__26__partial_array_destructorFv
 0x80105da0: __construct_new_array

 # runtime.c
 0x80105f24: __cvt_fp2unsigned

 # Result2D.cpp
 0x8014972c: getPad__8KartInfoFi

 # KartInfo.cpp
 0x801a8844: __ct__8KartInfoFv
 0x801a8898: __dt__Q28KartInfo13KartCharacterFv
 0x801a88d4: __ct__Q28KartInfo13KartCharacterFv
 0x801a8904: reset__Q28KartInfo13KartCharacterFv
 0x801a8914: reset__8KartInfoFv 
 0x801a896c: __dt__8KartInfoFv
 0x801a89c8: setDriver__8KartInfoFi7ECharIDP11KartGamePad
 0x801a8a90: setCharDB__Q28KartInfo13KartCharacterFPCQ28KartInfo7SCharDB
 0x801a8a98: getCharDB__8KartInfoF7ECharID
 0x801a8b68: getKartDB__8KartInfoF7EKartID
 0x801a8c40: getKartWeight__8KartInfoF7EKartID
 0x801a8c64: getDefaultDriver__8KartInfoF7EKartID
 0x801a8c88: getDefaultPartner__8KartInfoF7ECharID
 0x801a8cac: getDriverWeight__8KartInfoF7ECharID 
 0x801a8cd0: getDefaultKartID__8KartInfoF7ECharID
 0x801a8cf4: getPartnerKartID__8KartInfoF7ECharID
 0x801a8d18: isDefaultCharCombi__8KartInfoFv
 0x801a8d68: getCharID__Q28KartInfo13KartCharacterCFv
 0x801a8d84: getPartnerID__Q28KartInfo13KartCharacterCFv
 0x801a8da0: getYoungestPad__8KartInfoFv
 0x801a8e5c: getPadPort__11KartGamePadFv
 0x801a8e64: setPad__Q28KartInfo13KartCharacterFP11KartGamePad 
 0x801a8e6c: isAvailable__Q28KartInfo13KartCharacterCFv
 0x801a8eb4: getPadState__11KartGamePadFv
 0x801a8ebc: convPlayerKind__Q28KartInfo13KartCharacterFP11KartGamePad
 0x801a8f4c: getPadType__11KartGamePadFv
 #rodata
 0x803770f8: cBabyMarioCharDB__8KartInfo
 0x80377104: cBabyLuigiCharDB__8KartInfo
 0x80377110: cPatapataCharDB__8KartInfo
 0x8037711c: cNokonokoCharDB__8KartInfo
 0x80377128: cPeachCharDB__8KartInfo 
 0x80377134: cDaisyCharDB__8KartInfo 
 0x80377140: cMarioCharDB__8KartInfo
 0x8037714c: cLuigiCharDB__8KartInfo
 0x80377158: cWarioCharDB__8KartInfo
 0x80377164: cWaluigiCharDB__8KartInfo
 0x80377170: cDonkeyCharDB__8KartInfo 
 0x8037717c: cDonkeyJrCharDB__8KartInfo
 0x80377188: cYoshiCharDB__8KartInfo
 0x80377194: cCatherineCharDB__8KartInfo
 0x803771a0: cKoopaCharDB__8KartInfo
 0x803771ac: cKoopaJrCharDB__8KartInfo
 0x803771b8: cKinopioCharDB__8KartInfo
 0x803771c4: cKinopicoCharDB__8KartInfo
 0x803771d0: cKingTeresaCharDB__8KartInfo 
 0x803771dc: cBossPakkunCharDB__8KartInfo
 0x803771e8: cMustacheKartDB__8KartInfo
 0x803771f8: cMonkeyKartDB__8KartInfo
 0x80377208: cLizardKartDB__8KartInfo
 0x80377218: cSmallFishKartDB__8KartInfo
 0x80377228: cPrincessKartDB__8KartInfo
 0x80377238: cChildKartDB__8KartInfo
 0x80377248: cBadKartDB__8KartInfo
 0x80377258: cSatanKartDB__8KartInfo
 0x80377268: cLuigiKartDB__8KartInfo
 0x80377278: cDiddyKartDB__8KartInfo
 0x80377288: cCatherineKartDB__8KartInfo
 0x80377298: cPatapataKartDB__8KartInfo
 0x803772a8: cDaisyKartDB__8KartInfo
 0x803772b8: cBabyLuigiKartDB__8KartInfo
 0x803772c8: cWaluigiKartDB__8KartInfo
 0x803772d8: cKoopaJrKartDB__8KartInfo
 0x803772e8: cKinopioKartDB__8KartInfo
 0x803772f8: cKinopicoKartDB__8KartInfo
 0x80377308: cKingTeresaKartDB__8KartInfo
 0x80377318: cBossPakkunKartDB__8KartInfo
 0x80377328: cBonusKartDB__8KartInfo

 # stMath.cpp
 0x8021f5fc: createAllRandom__8stRandomFv
 0x8021f668: getRandomMax__8stRandomFUl
 0x8021f6e0: getArbitUnitVec__8stRandomFRQ29JGeometry8TVec3<f>ff
 0x8021f7f4: getArbitUnitVecSimple__8stRandomFRQ29JGeometry8TVec3<f>f
 0x8021f908: getArbitUnitVecXZ__8stRandomFRQ29JGeometry8TVec3<f>f
 0x8021f9a4: stGetRnd__FUl
 0x8021fa28: stSetRndPermission__FUlb
 0x8039d6f0: sRndMgr__8stRandom
 0x80416ac8: sMgr__8stRandom