global:
 # .init
 0x80003100: __check_pad3
 0x80003140: __set_debug_bba
 0x8000314c: __get_debug_bba
 0x80003154: __start
 0x800032b0: __init_registers
 0x80003340: __init_data
 0x80003400: __init_hardware
 0x80003424: __flush_cache
 0x80003458: memset
 0x80003488: __fill_mem
 0x80003540: memcpy
 0x80003590: TRK_memset
 0x800035c0: TRK_memcpy
 0x80005518: __TRK_reset

 # kartLocale.cpp:
 #.text
 0x800056c0: localize__10KartLocaleFv
 #.data
 0x803879c0: mscpaLanguageName__10KartLocale
 #.sdata
 0x80413f80: msCountry__10KartLocale
 0x80413f84: msRegion__10KartLocale
 0x80413f88: msDatingMode__10KartLocale
 #.sbss
 0x804156e0: msLanguage__10KartLocale
 0x804156e4: msSpeedUnit__10KartLocale
 0x804156e8: msVideoMode__10KartLocale
 0x804156ec: msVideoFrameMode__10KartLocale

 # random.cpp
 0x800693c8: __ct__Q25JMath13TRandom_fast_FUl

 0x800693d0: atan2___Q25JMath18TAtanTable<1024,f>CFff
 0x80069628: __sinit_JMATrigonometric_cpp
 0x800697e8: __ct__Q23std9pair<f,f>Fv

 0x803f2540: sincosTable___5JMath
 0x803f8580: atanTable___5JMath
 0x803f95a0: asinAcosTable___5JMath

 # JUTAssert.cpp
 0x80069af4: getSDevice__12JUTAssertionFv
 0x80069bd8: showAssert_f__12JUTAssertionFUlPCciPCce

 # JUTDbPrint.cpp
 0x8006b8c0: start__10JUTDbPrintFP7JUTFontP7JKRHeap
 0x8006b964: changeFont__10JUTDbPrintFP7JUTFont
 0x8006b97c: flush__10JUTDbPrintFv
 0x8006b9b4: flush__10JUTDbPrintFiiii
 0x8006bb10: drawString__10JUTDbPrintFiiiPCUc
 0x8006bbf8: JUTReport__FiiPCce
 0x8006bd1c: JUTReport__FiiiPCce

 # JUTGamePad.cpp
 0x8006fa08: __dt__10JUTGamePadFv

 # JSUList.cpp
 0x80078b2c: __ct__10JSUPtrLinkFPv
 0x80078b44: __dt__10JSUPtrLinkFv
 0x80078ba4: __ct__10JSUPtrListFb
 0x80078bdc: __dt__10JSUPtrListFv 
 0x80078c44: initiate__10JSUPtrListFv 
 0x80078c58: append__10JSUPtrListFP10JSUPtrLink
 0x80078d10: prepend__10JSUPtrListFP10JSUPtrLink
 0x80078dc8: insert__10JSUPtrListFP10JSUPtrLinkP10JSUPtrLink
 0x80078f98: remove__10JSUPtrListFP10JSUPtrLink
 0x80079048: getNthLink__10JSUPtrListCFUl

 # JKRExpHeap.cpp
 0x80081c4c: create__10JKRExpHeapFUlP7JKRHeapb
 0x80081d18: create__10JKRExpHeapFPvUlP7JKRHeapb

 # JKRHeap.cpp
 0x800840f8: becomeSystemHeap__7JKRHeapFv 
 0x80084108: becomeCurrentHeap__7JKRHeapFv
 0x80084118: destroy__7JKRHeapFv
 0x80084d9c: __nw__FUl
 0x80084e28: __nw__FUli
 0x80084eb8: __nw__FUlP7JKRHeapi
 0x80084fa4: __nwa__FUl
 0x80085030: __nwa__FUli
 0x800850c0: __nwa__FUlP7JKRHeapi
 0x800851ac: __dl__FPv
 0x800851d0: __dla__FPv

 # JKRAssertHeap.cpp
 0x800872ac: create__13JKRAssertHeapFP7JKRHeap

 # JASHeapCtrl.cpp
 0x800902a0: showAssert__12JUTAssertionFUlPCciPCc

 0x800a5fe0: __ct__Q29JGeometry8TVec3<f>Fv 

 # JUTGamePad.cpp
 0x8006f93c: __ct__10JUTGamePadFQ210JUTGamePad8EPadPort

 # OSError.c
 0x800eeaec: OSPanic

 0x800eddd0: LCQueueWait 

 # OSTime.c
 0x800f2d3c: OSGetTime

 # __ppc_eabi_init.cpp
 0x800f31b8: __init_user
 0x800f31d8: __init_cpp
 0x800f322c: _ExitProcess

 # NMWException.cp
 0x80105af8: __destroy_new_array
 0x80105b74: __destroy_arr
 0x80105bec: __construct_array
 0x80105ce8: __dt__26__partial_array_destructorFv
 0x80105da0: __construct_new_array

 # runtime.c
 0x80105f24: __cvt_fp2unsigned

 # EngineSound.cpp
 0x80118cac: getEngineType__11EngineSoundF7EKartID 

 # GameAudioMain.cpp
 0x8011e540: startSystemSe__Q29GameAudio4MainFUl 

 # Result2D.cpp
 0x80149534: getKartInfo__7RaceMgrFi
 0x8014972c: getPad__8KartInfoFi
 0x801497d4: getKartInfo__8RaceInfoFi
 0x80149bd4: getRaceMode__7RaceMgrCFv

 # SequenceInfo.cpp
 0x801528e8: rndDemo__12SequenceInfoFUl

 # Race2D.cpp
 0x801574a8: RCMGetCourse__Fv

 # Course.cpp
 0x80198f98: getManager__7RaceMgrFv
 0x80199688: zero__Q29JGeometry8TVec3<f>Fv
 0x80199f7c: getSectorDist__Q26Course6SectorCFv
 0x80199f84: getGeneration__Q26Course6SectorCFv
 0x80199f8c: isMainSector__Q26Course6SectorCFv
 0x8019a20c: searchSector__6CourseFs
 0x8019acf4: length__Q29JGeometry8TVec3<f>CFv

 0x8019ad14: sub__Q29JGeometry8TVec3<f>FRCQ29JGeometry8TVec3<f>RCQ29JGeometry8TVec3<f>
 0x8019ad48: PSVECSubtract__14JMathInlineVECFPC3VecPC3VecP3Vec 

 0x8019ab70: dot__Q29JGeometry8TVec3<f>CFRCQ29JGeometry8TVec3<f>
 0x8019abb0: normalize__Q29JGeometry8TVec3<f>Fv
 0x8019ac30: scale__Q29JGeometry8TVec3<f>Ff

 0x8019bcf0: getManager__8SysDebugFv
 0x8019caf4: getKartCtrl__8KartCtrlFv
 0x8019c368: getAudio__Q29GameAudio4MainFv 
 0x8019cc68: __ct__Q29JGeometry8TVec3<f>FRCQ29JGeometry8TVec3<f>

 0x8019d628: getBaseTRMtx__7ExModelFv

 0x8019e26c: calcGeneration__Q26Course6SectorFPQ26Course6Sector
 0x8019e2b8: getPrevSector__Q26Course6SectorFi
 0x8019e350: calcUnitDist__Q26Course6SectorFRCQ29JGeometry8TVec3<f>

 0x80199edc: getNextNum__Q26Course6SectorCFv 
 0x80199ee4: getNextSector__Q26Course6SectorFi

 # CrsGround.cpp
 0x801a17ac: __ct__9CrsGroundFP6Course
 0x801a18f0: search__9CrsGroundFRCQ29JGeometry8TVec3<f> 
 0x801a3268: getAddThickness__9CrsGroundCFv
 0x801a319c: getCameraCode__9CrsGroundCFv
 0x801a32c0: getStaggerCode__9CrsGroundCFv 
 0x801a3338: getSpiralCode__9CrsGroundCFv
 0x801a338c: getSplashCode__9CrsGroundCFv
 0x801a33e4: getSplashHeight__9CrsGroundFv 
 0x801a36c4: getAttrIndex__9CrsGroundCFv
 0x801a36cc: getAttribute__9CrsGroundCFv
 0x801a37e8: getWaterHeight__9CrsGroundFv

 # CrsData.cpp
 0x801a0064: getAddThickness__Q27CrsData6GroundCFv
 0x801a11f0: getKartNumber__8RaceInfoCFv

 # KartLoader.cpp
 0x801a808c: getExModelBody__10KartLoaderFv

 # KartInfo.cpp
 0x801a8844: __ct__8KartInfoFv
 0x801a8898: __dt__Q28KartInfo13KartCharacterFv
 0x801a88d4: __ct__Q28KartInfo13KartCharacterFv
 0x801a8904: reset__Q28KartInfo13KartCharacterFv
 0x801a8914: reset__8KartInfoFv 
 0x801a896c: __dt__8KartInfoFv
 0x801a89c8: setDriver__8KartInfoFi7ECharIDP11KartGamePad
 0x801a8a90: setCharDB__Q28KartInfo13KartCharacterFPCQ28KartInfo7SCharDB
 0x801a8a98: getCharDB__8KartInfoF7ECharID
 0x801a8b68: getKartDB__8KartInfoF7EKartID
 0x801a8c40: getKartWeight__8KartInfoF7EKartID
 0x801a8c64: getDefaultDriver__8KartInfoF7EKartID
 0x801a8c88: getDefaultPartner__8KartInfoF7ECharID
 0x801a8cac: getDriverWeight__8KartInfoF7ECharID 
 0x801a8cd0: getDefaultKartID__8KartInfoF7ECharID
 0x801a8cf4: getPartnerKartID__8KartInfoF7ECharID
 0x801a8d18: isDefaultCharCombi__8KartInfoFv
 0x801a8d68: getCharID__Q28KartInfo13KartCharacterCFv
 0x801a8d84: getPartnerID__Q28KartInfo13KartCharacterCFv
 0x801a8da0: getYoungestPad__8KartInfoFv
 0x801a8e5c: getPadPort__11KartGamePadFv
 0x801a8e64: setPad__Q28KartInfo13KartCharacterFP11KartGamePad 
 0x801a8e6c: isAvailable__Q28KartInfo13KartCharacterCFv
 0x801a8eb4: getPadState__11KartGamePadFv
 0x801a8ebc: convPlayerKind__Q28KartInfo13KartCharacterFP11KartGamePad
 0x801a8f4c: getPadType__11KartGamePadFv
 #rodata
 0x803770f8: cBabyMarioCharDB__8KartInfo
 0x80377104: cBabyLuigiCharDB__8KartInfo
 0x80377110: cPatapataCharDB__8KartInfo
 0x8037711c: cNokonokoCharDB__8KartInfo
 0x80377128: cPeachCharDB__8KartInfo 
 0x80377134: cDaisyCharDB__8KartInfo 
 0x80377140: cMarioCharDB__8KartInfo
 0x8037714c: cLuigiCharDB__8KartInfo
 0x80377158: cWarioCharDB__8KartInfo
 0x80377164: cWaluigiCharDB__8KartInfo
 0x80377170: cDonkeyCharDB__8KartInfo 
 0x8037717c: cDonkeyJrCharDB__8KartInfo
 0x80377188: cYoshiCharDB__8KartInfo
 0x80377194: cCatherineCharDB__8KartInfo
 0x803771a0: cKoopaCharDB__8KartInfo
 0x803771ac: cKoopaJrCharDB__8KartInfo
 0x803771b8: cKinopioCharDB__8KartInfo
 0x803771c4: cKinopicoCharDB__8KartInfo
 0x803771d0: cKingTeresaCharDB__8KartInfo 
 0x803771dc: cBossPakkunCharDB__8KartInfo
 0x803771e8: cMustacheKartDB__8KartInfo
 0x803771f8: cMonkeyKartDB__8KartInfo
 0x80377208: cLizardKartDB__8KartInfo
 0x80377218: cSmallFishKartDB__8KartInfo
 0x80377228: cPrincessKartDB__8KartInfo
 0x80377238: cChildKartDB__8KartInfo
 0x80377248: cBadKartDB__8KartInfo
 0x80377258: cSatanKartDB__8KartInfo
 0x80377268: cLuigiKartDB__8KartInfo
 0x80377278: cDiddyKartDB__8KartInfo
 0x80377288: cCatherineKartDB__8KartInfo
 0x80377298: cPatapataKartDB__8KartInfo
 0x803772a8: cDaisyKartDB__8KartInfo
 0x803772b8: cBabyLuigiKartDB__8KartInfo
 0x803772c8: cWaluigiKartDB__8KartInfo
 0x803772d8: cKoopaJrKartDB__8KartInfo
 0x803772e8: cKinopioKartDB__8KartInfo
 0x803772f8: cKinopicoKartDB__8KartInfo
 0x80377308: cKingTeresaKartDB__8KartInfo
 0x80377318: cBossPakkunKartDB__8KartInfo
 0x80377328: cBonusKartDB__8KartInfo

 # KartChecker.cpp
 0x801a9040: __ct__14KartChkUsrPageFP11KartChecker
 0x801a9084: draw__14KartChkUsrPageFv
 0x801a9450: getRank__11KartCheckerCFv
 0x801a9458: getShadowRate__7CrsAreaCFv
 0x801a9478: getRate__7CrsAreaCFv
 0x801a9480: getMaterial__9CrsGroundCFv
 0x801a9488: isLapRenewal__11KartCheckerCFv
 0x801a9490: printPass__11KartCheckerFii
 0x801a9514: getTrackSectorDist__6CourseCFv
 0x801a951c: searchLight__7CrsAreaFRCQ29JGeometry8TVec3<f>
 0x801a9544: searchCamera__7CrsAreaFRCQ29JGeometry8TVec3<f>
 0x801a956c: searchRoof__7CrsAreaFRCQ29JGeometry8TVec3<f>
 0x801a9594: searchShadow__7CrsAreaFRCQ29JGeometry8TVec3<f>
 0x801a95bc: getVelocity__9CrsGroundCFPQ29JGeometry8TVec3<f>
 0x801a95e8: set<f>__Q29JGeometry8TVec3<f>FRCQ29JGeometry8TVec3<f>
 0x801a9604: __ct__11KartCheckerFiP8KartInfoii
 0x801a97d8: setLapChecking__11KartCheckerFv
 0x801a97e8: setDemoRank__11KartCheckerFv
 0x801a97f8: setRabbitCtrl__11KartCheckerFv
 0x801a9808: setBombCtrl__11KartCheckerFv
 0x801a9818: setBalloonCtrl__11KartCheckerFv
 0x801a9828: __ct__8RaceTimeFv
 0x801a9858: reset__8RaceTimeFv
 0x801a9868: reset__11KartCheckerFv
 0x801a99b4: getWinFrame__23GeoRabbitMarkSupervisorCFv 
 0x801a99c4: getSupervisor__13GeoRabbitMarkFv
 0x801a99cc: setRank__11KartCheckerFi
 0x801a99d4: tstDemoRank__11KartCheckerCFv
 0x801a99e0: clrRank__11KartCheckerFv
 0x801a99ec: zero__8RaceTimeFv
 0x801a99f8: clrCheckPointIndex__11KartCheckerFv
 0x801a9abc: getStartSector__6CourseCFv
 0x801a9ac4: setPlayerKartColor__11KartCheckerFP8KartInfo
 0x801a9bfc: isLANMode__7RaceMgrCFv
 0x801a9c20: isLANMode__8RaceInfoFv
 0x801a9c28: createGamePad__11KartCheckerFP8KartInfo
 0x801a9cb4: __ct__11KartGamePadFQ210JUTGamePad8EPadPortQ211KartGamePad7PadPortQ211KartGamePad7PadTypeQ211KartGamePad8PadState
 0x801a9d08: searchCurrentSector__11KartCheckerFPfRCQ29JGeometry8TVec3<f>PQ26Course6Sectori
 0x801aa050: isInvalid__Q26Course6SectorCFv
 0x801aa064: getPrevNum__Q26Course6SectorCFv
 0x801aa06c: getTotalSectorNumber__6CourseCFv
 0x801aa074: isInsideSector__11KartCheckerFf
 0x801aa09c: getSector__6CourseCFi
 0x801aa138: isDiv__Q26Course6SectorCFv
 0x801aa140: checkKart__11KartCheckerFv
 0x801aa240: tstRabbitCtrl__11KartCheckerCFv
 0x801aa24c: isBombPointFull__11KartCheckerCFv
 0x801aa268: tstBombCtrl__11KartCheckerCFv
 0x801aa274: set__8RaceTimeFi
 0x801aa294: isDead__11KartCheckerCFv
 0x801aa2b4: tstDead__11KartCheckerCFv
 0x801aa2c0: isAvailable__8RaceTimeCFv
 0x801aa2dc: tstBalloonCtrl__11KartCheckerCFv
 0x801aa2e8: tstLapChecking__11KartCheckerCFv
 0x801aa2f4: checkKartLap__11KartCheckerFv
 0x801aa638: getTotalPriorDist__Q26Course6SectorCFv
 0x801aa640: getMainSector__Q26Course6SectorFv
 0x801aa648: getSectorID__10JugemPointCFv
 0x801aa654: getMainSector__6CourseCFi
 0x801aa6f0: isRevSearchEnable__Q26Course6SectorCFv
 0x801aa704: isUDValid__11KartCheckerFv
 0x801aa734: getBestLapTime__11KartCheckerFv
 0x801aa7ac: isLittle__8RaceTimeCFRC8RaceTime
 0x801aa7cc: checkLap__11KartCheckerFb
 0x801aab60: isComKart__8KartInfoCFv
 0x801aab84: isComDriver__8KartInfoCFi
 0x801aac20: isComPlayer__Q28KartInfo13KartCharacterCFv
 0x801aac30: clrPass__11KartCheckerFi
 0x801aac6c: setGoalTime__11KartCheckerFv
 0x801aacb8: __as__8RaceTimeFRC8RaceTime 
 0x801aacc4: setGoal__11KartCheckerFv
 0x801aacd8: isGoal__11KartCheckerCFv
 0x801aace0: incLap__11KartCheckerFv
 0x801aacfc: isPass__11KartCheckerFi
 0x801aadc4: getShortcutID__Q26Course6SectorCFv 
 0x801aadd0: setLapTime__11KartCheckerFv
 0x801ab050: sub__8RaceTimeFRC8RaceTimeRC8RaceTime
 0x801ab064: get__8RaceTimeCFv
 0x801ab06c: sub__8RaceTimeFi
 0x801ab07c: set__8RaceTimeFRC8RaceTime
 0x801ab09c: sub__Q29JGeometry8TVec3<f>FRCQ29JGeometry8TVec3<f> 
 0x801ab0c0: isMaxTotalTime__11KartCheckerCFv
 0x801ab0f0: __ct__8RaceTimeFRC8RaceTime
 0x801ab0fc: setFrame__8RaceTimeFi
 0x801ab128: setForceGoal__11KartCheckerFv
 0x801ab324: setPass__11KartCheckerFi 
 0x801ab438: isPassAll__11KartCheckerFi
 0x801ab4a8: incTime__11KartCheckerFv
 0x801ab4f8: isReverse__11KartCheckerFv 
 0x801ab5a4: getBNormal__Q26Course6SectorFPQ29JGeometry8TVec3<f>
 0x801ab5fc: getKartLoader__7RaceMgrCFi
 0x801ab694: isFinalLapRenewal__11KartCheckerCFv
 0x801ab6e4: isFinalLap__11KartCheckerCFv
 0x801ab700: isCurrentLapTimeRenewal__11KartCheckerFv
 0x801ab788: getBestLapTime__7RaceMgrFv 
 0x801ab790: getLapTime__11KartCheckerFi 
 0x801ab82c: isBestLapTimeRenewal__11KartCheckerFv
 0x801ab8bc: isBestTotalTimeRenewal__11KartCheckerFi
 0x801ab92c: getBestTotalTime__7RaceMgrFi
 0x801ab9c4: getTotalTime__11KartCheckerFv
 0x801ab9cc: incBalloon__11KartCheckerFv
 0x801aba38: tstFixMiniPoint__11KartCheckerCFv 
 0x801aba44: decBalloon__11KartCheckerFv
 0x801abb00: setDead__11KartCheckerFv
 0x801abb10: checkRaceEnd__7RaceMgrFv
 0x801abb34: incMyBombPoint__11KartCheckerFii
 0x801abd14: GetKartCtrl__Fv
 0x801abd34: incYourBombPoint__11KartCheckerFiii
 0x801abd7c: getKartChecker__7RaceMgrCFi
 0x801abe14: setBombEvent__11KartCheckerFQ211KartChecker10EBombEventP7ItemObj
 0x801abf28: getDirectHitKartNo__7ItemObjCFv
 0x801abf30: getKartReaction__7ItemObjCFv
 0x801abf38: getOwnerNum__7ItemObjCFv
 0x801abf40: getRobberyItemNumber__11KartCheckerFv
 0x801abf9c: GetItemObjMgr__Fv
 0x801abfbc: getItemObjMgr__10ItemObjMgrFv 
 0x801abfc4: releaseRabbitMark__11KartCheckerFv
 0x801ac048: isRabbitWinner__11KartCheckerCFv
 0x801ac05c: isRabbit__11KartCheckerCFv
 0x801ac0bc: calcRabbitTime__11KartCheckerFv
 0x801ac1ec: resumeRabbitTimer__11KartCheckerFv
 0x801ac1fc: getWinTime__23GeoRabbitMarkSupervisorCFv 
 0x801ac204: getUpwardMSec__8RaceTimeCFv
 0x801ac210: tstStillRabbitTimer__11KartCheckerCFv
 0x801ac21c: __ct__10LapCheckerFv 
 0x801ac24c: reset__10LapCheckerFv 
 0x801ac264: start__10LapCheckerFPQ26Course6Sector
 0x801ac26c: calc__10LapCheckerFRCQ29JGeometry8TVec3<f>
 0x801ac3cc: getTrackSectorNumber__6CourseCFv
 0x801ac3d4: isUDValid__10LapCheckerFv
 0x801ac404: __dt__11KartGamePadFv 
 0x801ac45c: __dt__14KartChkUsrPageFv 

 0x80395c98: sPlayerKartColorTable__11KartChecker
 0x80395cb8: __vt__11KartGamePad
 0x80395cc4: __vt__14KartChkUsrPage

 0x80414618: sBalForbiddenTime__11KartChecker
 0x8041461a: sBombPointDirect__11KartChecker
 0x8041461c: sBombPointSpin__11KartChecker
 0x8041461e: sBombPointIndirect__11KartChecker
 0x80414620: sBombPointAttacked__11KartChecker
 0x80414622: sBombPointFull__11KartChecker
 0x80414624: sBombPointFullS__11KartChecker
 0x80414626: sBombPointFullL__11KartChecker

 0x804163a0: sBombPointCrushOneself__11KartChecker

 # RaceMgr.cpp
 0x801aff04: getRaceMode__8RaceInfoCFv

 # CrsArea.cpp
 0x801b35f8: __ct__7CrsAreaFv
 0x801b366c: search__7CrsAreaFUcRCQ29JGeometry8TVec3<f>
 0x801b37c8: getCameraID__7CrsAreaCFv
 0x801b3908: getEchoRate__7CrsAreaFv
 0x801b39c0: getLightParamID__7CrsAreaFv
 0x801b3a4c: getLightParamID__Q26Course4AreaCFv

 # RaceInfo.cpp
 0x801b5098: __ct__8RaceInfoFv
 0x801b5124: reset__8RaceInfoFv
 0x801b5264: setConsoleTarget__8RaceInfoFiib
 0x801b530c: settingForWaitDemo__8RaceInfoFb
 0x801b55a0: getDemoKart__12SequenceInfoFiR7ECharIDR7ECharIDR7EKartID
 0x801b5658: setRandomSeed__8RaceInfoFUl
 0x801b5660: setRivalKartNo__8RaceInfoFii
 0x801b5750: settingForAwardDemo__8RaceInfoFv
 0x801b588c: setAwardKartNo__8RaceInfoFi
 0x801b5894: setGpCup__8RaceInfoF10ERaceGpCup
 0x801b589c: settingForStaffRoll__8RaceInfoFb
 0x801b59a8: setRace__8RaceInfoF9ERaceModeiiii
 0x801b5a34: setKart__8RaceInfoFi7EKartID7ECharIDP11KartGamePad7ECharIDP11KartGamePad
 0x801b5b8c: setKartID__8KartInfoF7EKartID
 0x801b5bc0: setRaceLevel__8RaceInfoF10ERaceLevel
 0x801b5be4: shuffleRandomSeed__8RaceInfoFv 
 0x801b5c24: get__Q25JMath13TRandom_fast_Fv
 0x801b5c48: __ct__Q25JMath33TRandom_<Q25JMath13TRandom_fast_>FUl
 0x801b5c78: shuffleStartNo__8RaceInfoFv
 0x801b5d70: hideConsole__8RaceInfoFUl
 0x801b5e14: __sinit_RaceInfo_cpp
 0x801b5f1c: __dt__8RaceInfoFv 

 0x80395e08: sAwardDebugKartIDTable__8RaceInfo
 0x80395e14: sAwardDebugDriver1IDTable__8RaceInfo
 0x80395e20: sAwardDebugDriver2IDTable__8RaceInfo

 0x80414630: sForceDemoNo__8RaceInfo
 0x80414634: sForceRandomSeed__8RaceInfo
 0x80414638: sAwardDebugLevel__8RaceInfo
 0x8041463c: sAwardDebugRank__8RaceInfo

 0x804163d0: sWaitDemoSelector__8RaceInfo
 0x804163d4: sAwardDebugCup__8RaceInfo

 # SysDebug.cpp
 0x801b2834: createHeapInfo__8SysDebugFP7JKRHeapPc
 0x801b2900: destroyHeapInfo__8SysDebugFP7JKRHeap 

 0x801b2df4: appendPage__8SysDebugFP12SysDbUsrPage
 0x801b34c0: __ct__12SysDbUsrPageFv

 0x801b3584: __dt__12SysDbUsrPageFv 

 0x804163b0: sManager__8SysDebug

 # Scene.cpp
 0x8013c1e8: __ct__5SceneFP10JKRArchiveP7JKRHeap
 0x8013c270: __dt__5SceneFv
 0x80394b70: __vt__5Scene

 # GeoItemCar.cpp
 0x801c2850: scale__Q29JGeometry8TVec3<f>FfRCQ29JGeometry8TVec3<f> 

 # GeoRabbitMark.cpp

 0x801cd674: getRabbitKartNo__23GeoRabbitMarkSupervisorFv
 0x801cd680: release__23GeoRabbitMarkSupervisorFv

 0x801cd740: startWinnerEffect__23GeoRabbitMarkSupervisorFv

 0x804164b8: sSupervisorCreateNum__13GeoRabbitMark 
 0x804164bc: sSupervisor__13GeoRabbitMark

# RaceDirector.cpp
 0x801c8a24: checkRaceEnd__12RaceDirectorFv

 # RaceTime.cpp
 0x801d9e4c: get__8RaceTimeCFPiPiPi

# system.cpp
 0x80416968: mspDisplay__6System
 0x8041696c: mspAppHeap__6System
 0x80416970: msDvdState__6System
 0x80416974: msRenderMode__6System
 0x80416978: mspSendTask__6System
 0x8041697c: mspRecvTask__6System
 0x80416980: mspAramTask__6System
 0x80416984: mspLoTask__6System
 0x80416988: mspJ2DPrint__6System
 0x8041698c: mspJ2DOrtho__6System
 0x80416990: mspAudioHeap__6System

# systemData.cpp
 0x80205c2c: __sinit_systemData_cpp
 0x8037d938: sc3DViewPort__10SystemData
 0x8037d948: sc3DScissor__10SystemData
 0x8037d958: sc3DAwardScissor__10SystemData
 0x8037d968: scOrtho__10SystemData
 0x8037d978: sc3DViewPortSub__10SystemData
 0x8037d988: sc3DScissorSub__10SystemData
 0x8037d998: scNtscInt448Df__10SystemData
 0x8037d9d4: scNtscInt448__10SystemData
 0x8037da10: scNtscProg448Soft__10SystemData
 0x8037da4c: scNtscProg448__10SystemData
 0x8039cd28: sca3DViewPortDiv2__10SystemData
 0x8039cd48: sca3DScissorDiv2__10SystemData 
 0x8039cd68: sca3DViewPortDiv4__10SystemData
 0x8039cda8: sca3DScissorDiv4__10SystemData
 0x80416a00: scAspect__10SystemData
 0x80416a04: scAspectDiv2__10SystemData
 0x80416a08: scAspectSub__10SystemData 
 0x8041b758: scNumStandardHeaps__10SystemData
 0x8041b75c: scDefaultFifoSize__10SystemData
 0x8041b760: scSystemHeapSize__10SystemData
 0x8041b764: scAudioHeapSize__10SystemData
 0x8041b768: scAudioAramSize__10SystemData

 # GameApp.cpp
 0x801f74dc: __ct__7GameAppFUlPCcPv
 0x801f7580: __dt__7GameAppFv
 0x801f75ec: draw__7GameAppFv
 0x801f75f0: calc__7GameAppFv
 0x8013c5d0: reset__7GameAppFv 
 0x801d7a88: getHeap__7GameAppFv

 0x8039c460: __vt__7GameApp

 # main.cpp
 0x801f75f4: main
 
 # system.cpp
 0x801feba0: init__6SystemFv
 0x801ff334: run__6SystemFv

 # SequenceInfo.cpp
 0x803fba80: gSequenceInfo

 # SaveFile.cpp
 0x8020c230: getCRC__8SaveFileFPUcPUc
 0x80407334: msaCRCTable__8SaveFile
 0x80416a48: msCRCTableComputed__8SaveFile

 # stMath.cpp
 0x8021f5fc: createAllRandom__8stRandomFv
 0x8021f668: getRandomMax__8stRandomFUl
 0x8021f6e0: getArbitUnitVec__8stRandomFRQ29JGeometry8TVec3<f>ff
 0x8021f7f4: getArbitUnitVecSimple__8stRandomFRQ29JGeometry8TVec3<f>f
 0x8021f908: getArbitUnitVecXZ__8stRandomFRQ29JGeometry8TVec3<f>f
 0x8021f9a4: stGetRnd__FUl
 0x8021fa28: stSetRndPermission__FUlb
 0x8039d6f0: sRndMgr__8stRandom
 0x80416ac8: sMgr__8stRandom

 # ItemObjMgr.cpp
 0x80241928: getRobberyItemNum__10ItemObjMgrFiUc

 # kartCtrl.cpp
 0x802e1968: getDriverPad__11KartCheckerCFi

 # kartCtrlInfo.cpp
 0x802f2994: GetBodyPos__8KartCtrlFiPQ29JGeometry8TVec3<f>

 0x802f34dc: GetKartSoundMgr__8KartCtrlFi 

 0x80416b50: gItemMgr__10ItemObjMgr