name: Build

on:
  push:
  pull_request:

jobs:
  build:
    container: ghcr.io/swarejonge/mkdd-build:main

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [MarioClub_us]

    steps:
    # Checkout the repository (shallow clone)
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    # Set Git config
    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    # Copy the original files to the workspace
    - name: Prepare
      run: cp -R /orig .

    # Build the project
    - name: Build
      run: |
        python configure.py --version ${{ matrix.version }} \
            --binutils /binutils --compilers /compilers
        ninja all_source build/${{ matrix.version }}/progress.json

    # Upload progress if we're on the main branch
    - name: Upload progress
      if: github.ref == 'refs/heads/main'
      continue-on-error: true
      env:
        PROGRESS_API_KEY: ${{ secrets.PROGRESS_API_KEY }}
      run: |
        python tools/upload_progress.py -b https://progress.decomp.club/ \
          -p mkdd -v ${{ matrix.version }} \
          build/${{ matrix.version }}/progress.json
